# To be used for CI

disabled_rules:
    - line_length
    - file_length
    - function_body_length
    - type_body_length
    - trailing_whitespace
    - cyclomatic_complexity
    - identifier_name

included:
    - Samples
    - Source

excluded:
    - Vendor
    - Samples/Playground.playground

reporter: "xcode"
